name: CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches : [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Execute Gradle build
        run: ./gradlew clean build -x test -Pprofile=dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/trade_market:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/trade_market:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USER }}/trade_market:buildcache,mode=max


