name: CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches : [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Execute Gradle build
        run: ./gradlew clean build -x test -Pprofile=dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and release to DockerHub
        env:
          NAME: ${{secrets.DOCKER_USER}}
          REPO: trade_market
        run: |
          docker build --platform linux/amd64 -t $NAME/$REPO -f ./DockerFile .
          docker push $NAME/$REPO:latest
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{secrets.EC2_HOST}}
          key: ${{secrets.EC2_KEY}}
          script: |
            docker stop trade_market_be
            docker rm trade_market_be
            docker rmi ${{secrets.DOCKER_USER}}/trade_market:latest
            docker pull ${{secrets.DOCKER_USER}}/trade_market:latest
            docker run --name trade_market_be -d -p 8080:8080 ${{secrets.DOCKER_USER}}/trade_market:latest


