name: CI/CD
on:
  push:
    branches: [master]
  pull_request:
    branches : [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
          submodules: true
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Execute Gradle build
        run: ./gradlew clean build -x test -Pprofile=dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and release to DockerHub
        env:
          NAME: ${{secrets.DOCKER_USER}}
          APP: trade_market
          NIGNIX: nginx
        run: |
          docker build --platform linux/amd64 -t $NAME/$APP -f ./DockerFile .
          docker build --platform linux/amd64 -t $NAME/$NGINX -f ./nginx/DockerFile .
          docker push $NAME/$APP:latest
          docker push $NAME/$NGINX:latest
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        env:
          APP: "trade_market"
          NIGNIX: "nginx"
          COMPOSE: "/home/ubuntu/compose/docker-compose.yml"
        with:
          username: ubuntu
          host: ${{secrets.EC2_HOST}}
          key: ${{secrets.EC2_KEY}}
          envs: REPO, CONTNAME, COMPOSE
          script_stop: true
          script: |
            sudo docker-compose -f $COMPOSE down --rmi all 
            sudo docker pull ${{secrets.DOCKER_USER}}/$APP:latest
            sudo docker pull ${{secrets.DOCKER_USER}}/$NIGNIX:latest
            sudo docker-compose -f $COMPOSE up -d


